# Generated by Django 4.2.16 on 2025-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0002_alter_reportcard_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
