# Generated by Django 4.2.16 on 2025-05-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_api', '0003_reportcard_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='average_marks',
            new_name='obtained_marks_total',
        ),
    ]
